apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcode-coordinator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcode-coordinator
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "patch", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcode-coordinator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mcode-coordinator
subjects:
  - kind: ServiceAccount
    name: mcode-coordinator
