apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcode-sweep-results
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ibmc-vpc-block-retain-general-purpose
  resources:
    requests:
      storage: 20Gi
