apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcode-results
spec:
  # RWX storage enables true parallel sharded Jobs (multiple pods writing to /results at once).
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # IBM Cloud VPC file storage (NFS) is RWX-capable.
  # Other common options might include "nfs-client" or "efs-sc" depending on your platform.
  storageClassName: ibmc-vpc-file-regional
