apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcode-results
spec:
  # For parallel sharded Jobs, prefer RWX (file/NFS) storage.
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # Uncomment and set if your cluster has multiple storage classes.
  # storageClassName: <rwx-storage-class>

